1. NumPy array to store player names, game scores, and levels reached

In [1]:
import numpy as np

player_data = np.array([
    ["Alice", 250, 5],
    ["Bob", 300, 8],
    ["Charlie", 200, 6]
])

2. Update the score of the player who has reached the highest level

In [2]:
levels = player_data[:, 2].astype(int)  
highest_level_index = np.argmax(levels)  

print('Player at highest level: ', player_data[highest_level_index])


player_data[highest_level_index, 1] = str(int(player_data[highest_level_index, 1]) + 50)  # Update score by 50

print('After updation:')
print('Player at highest level: ', player_data[highest_level_index])

Player at highest level:  ['Bob' '300' '8']
After updation:
Player at highest level:  ['Bob' '350' '8']


3. Append a new player's data (name, score, level) to the array. 

In [ ]:
new_player = np.array(["Dave", 220, 7])
print(player_data, '\n')
player_data = np.append(player_data, new_player)
print(player_data, '\n')
player_data = player_data.reshape(4,3)
print(player_data)

[['Alice' '250' '5']
 ['Bob' '350' '8']
 ['Charlie' '200' '6']] 

['Alice' '250' '5' 'Bob' '350' '8' 'Charlie' '200' '6' 'Dave' '220' '7'] 

[['Alice' '250' '5']
 ['Bob' '350' '8']
 ['Charlie' '200' '6']
 ['Dave' '220' '7']]


4. Insert a new player's score at a specific index within the array.

In [4]:
new_score = np.array(["Eve", 270, 4])
insert_index = 2  
print(player_data, '\n')
player_data = np.insert(player_data, insert_index, new_score, axis=0)
print(player_data)

[['Alice' '250' '5']
 ['Bob' '350' '8']
 ['Charlie' '200' '6']
 ['Dave' '220' '7']] 

[['Alice' '250' '5']
 ['Bob' '350' '8']
 ['Eve' '270' '4']
 ['Charlie' '200' '6']
 ['Dave' '220' '7']]


5. Delete the player with the lowest score from the dataset.

In [5]:
scores = player_data[:, 1].astype(int)  
lowest_score_index = np.argmin(scores)  
print(player_data, '\n')
player_data = np.delete(player_data, lowest_score_index, axis=0)
print(player_data)

[['Alice' '250' '5']
 ['Bob' '350' '8']
 ['Eve' '270' '4']
 ['Charlie' '200' '6']
 ['Dave' '220' '7']] 

[['Alice' '250' '5']
 ['Bob' '350' '8']
 ['Eve' '270' '4']
 ['Dave' '220' '7']]


In [6]:
visitors = np.array([120, 150, 80, 200, 175])
pages_viewed = np.array([300, 500, 200, 700, 650])


In [14]:
import copy
visitors_shallow_copy = visitors[:]
pages_viewed_deep_copy = pages_viewed.copy()
print(visitors_shallow_copy)
print(pages_viewed_deep_copy)


[120 150  80 200 175]
[300 500 200 700 650]


In [15]:
combined_data = np.concatenate((visitors, pages_viewed))
print(combined_data)

[120 150  80 200 175 300 500 200 700 650]


In [17]:
threshold = 100
high_traffic = combined_data[combined_data > threshold]
low_traffic = combined_data[combined_data <= threshold]
print(high_traffic)
print(low_traffic)


[120 150 200 175 300 500 200 700 650]
[80]


In [ ]:
visitors[0] = 130  
pages_viewed[0] = 600  

print("Original Copy of Visitors:", visitors) 

print("Shallow Copy of Visitors:", visitors_shallow_copy) 

print("\nOriginal Copy of pages viewed:", pages_viewed) 

print("Deep Copy of Pages Viewed:", pages_viewed_deep_copy)  

Original Copy of Visitors: [130 150  80 200 175]
Shallow Copy of Visitors: [130 150  80 200 175]

Original Copy of pages viewed: [600 500 200 700 650]
Deep Copy of Pages Viewed: [300 500 200 700 650]
